name: RSS to LINE

on:
  schedule:
    - cron: "*/30 * * * *"  # 每30分鐘
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_TO: ${{ secrets.LINE_TO }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py
